Approve weekly report functionality
massproduction/solinor-invoice-checking pull request #4
Opened 2017-10-13 10:55 UTC by nakkje

Enables team lead to mark a weekly report as "checked"

2017-10-13 12:47 UTC, massproduction requested changes

2017-10-13 12:47 UTC, massproduction commented on invoices/models.py
> +        print(comment)
Remove print

2017-10-13 12:48 UTC, nakkje commented on invoices/models.py
> +        print(comment)
:trollface:

2017-10-16 06:22 UTC, massproduction approved these changes

2017-10-16 06:22 UTC, merged