Weekly report summary input
massproduction/solinor-invoice-checking pull request #9
Opened 2017-10-17 11:43 UTC by massproduction

2017-10-17 12:15 UTC, nakkje requested changes
![image](https://user-images.githubusercontent.com/2685330/31664394-e549402e-b34d-11e7-9e37-24172c0b857a.png)
It's somewhat ugly, and IMO it's not super clear that it's possible to add n rows by saving between each

2017-10-17 13:26 UTC, massproduction commented
@nakkje fixed the buttons.

2017-10-17 16:09 UTC, nakkje commented
IMHO it would be much better if the summary was implemented as a WeeklyReportComment. Would get latest edits nicely too (and undo etc in the future if requested) 
I did it for change of scope thingy https://github.com/massproduction/solinor-invoice-checking/blob/weekly-report-change-of-scope/invoices/views.py#L736
https://github.com/massproduction/solinor-invoice-checking/blob/weekly-report-change-of-scope/invoices/views.py#L695
(that branch is still missing getting the latest change of scope 'comment' from previous weekly reports in case it's missing from current one, thus no pr yet)

2017-10-18 06:19 UTC, massproduction commented
If it's just a single field then I don't see the point of implementing it as a different model.

2017-10-18 11:43 UTC, nakkje requested changes

2017-10-18 11:43 UTC, nakkje commented on invoices/views.py
> +def delete_weekly_report_summary(request, weekly_report_id=None, weekly_report_comment_id=None):
shouldn't it be delete_weekly_report_comment?

2017-10-18 11:43 UTC, nakkje commented on invoices/views.py
> +        comment.delete()
add message to request

2017-10-18 11:56 UTC, nakkje approved these changes

2017-10-18 11:56 UTC, merged